apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      automountServiceAccountToken: false
      containers:
        - name: minio
          image: minio/minio:RELEASE.2025-07-23T15-54-02Z-cpuv1
          args:
            - server
            - /data
            - --console-address
            - ':9001'
          ports:
            - containerPort: 9000
            - containerPort: 9001
          envFrom:
            - secretRef:
                name: minio-secrets
          resources:
            requests:
              cpu: '250m'
              memory: '512Mi'
              ephemeral-storage: '1Gi'
            limits:
              memory: '1Gi'
              ephemeral-storage: '2Gi'
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: minio-data-pvc
