apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-odoo-data-pv
  namespace: onnasoft-odoo
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/postgres-odoo-onnasoft
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - juliotorres-pc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-odoo-data-pvc
  namespace: onnasoft-odoo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-storage
