apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: onnasoft-odoo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      terminationGracePeriodSeconds: 60
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      nodeSelector:
        kubernetes.io/hostname: juliotorres-pc
      containers:
        - name: postgres
          image: pgvector/pgvector:0.8.0-pg17-bookworm
          ports:
            - containerPort: 5432
          resources:
            limits:
              cpu: "16"
              memory: "8Gi"
              ephemeral-storage: "4Gi"
            requests:
              cpu: "100m"
              memory: "4Gi"
              ephemeral-storage: "4Gi"
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          envFrom:
            - secretRef:
                name: onnasoft-odoo-secret
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-odoo-data-pvc
